### ISSUE TITLE
Bug: deleting an object in line mode, tree-sitter mode etc knocks you back into word mode

### ISSUE THREAD

**Issue by Richiban** [DnailZ/oomotion_vscode#11]
Steps to reproduce:
1. Enter `NORMAL - line` mode
2. Select a line using the arrow keys as normal
3. Press `d` to delete the line
4. Note that the editor is now in `NORMAL - word` 

This feels an awful lot like a bug to me, but it _could_ be intended behaviour, in which case I'd appreciate if it could be customisable!

**Comment by DnailZ** [comment]
I'm sorry that's by design. Vim users always use some thing like `d d` to delete a line swiftly, so I thought using `x d` to remove a line and return to word mode would be a good idea. 

I previously don't think there will be so many people trying to use this so I haven't provide enough command-level configuration. I will consider more detailed configurations in future version.

**Comment by Richiban** [comment]
Thank you! I have to say, out of all the modal editor extensions I've tried out on VS Code this is by far my favourite :). I much prefer the way you choose what kind of subject you're working on (word, line etc) and then move the selection with the normal movement keys. It's like Helix but taken to the next level :)
